apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sqlserver.fullname" . }}
  labels:
    {{- include "sqlserver.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
