apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlserver.fullname" . }}
  labels:
    {{- include "sqlserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 1433
    protocol: TCP
    name: mssql
  selector:
    app: {{ include "sqlserver.name" . }}
